image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start development environment
    before: |
      eval $(command gp env -e)
      SHELL=$(which bash) npx --yes @teambit/bvm install
      source ~/.bashrc
      bit config set analytics_reporting false
      bit config set anonymous_reporting false
      bit install
      pnpm config set auto-install-peers true
      git config pull.rebase false
    command: |
      bit config set user.token $BIT_TOKEN
      bit init
      bit scope set $BIT_SCOPE
      bit import $BIT_IMPORT
      bit start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    description: Workspace components

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - christian-kohler.npm-intellisense
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - meganrogge.template-string-converter
    - leodevbro.blockman
    - Gruntfuggly.todo-tree
    - unifiedjs.vscode-mdx
    - bradlc.vscode-tailwindcss
    - PulkitGangwar.nextjs-snippets
    - PKief.material-icon-theme
    - TeamHub.teamhub
