image:
  file: .gitpod.Dockerfile

tasks:
  - name: Start development environment
    before: |
      eval $(command gp env -e)
      doppler configure set token $DOPPLER_LOCAL_TOKEN --no-check-version
      doppler setup --project dechea --config dev --no-check-version
      pnpm config set auto-install-peers true
      pnpm config set '@dechea:registry' https://node.bit.cloud
      doppler run --command='npm config set "//node.bit.cloud/:_authToken" $BIT_TOKEN'
      git config pull.rebase false
    command: |
      npx @teambit/bvm install --yes

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
#     description: Website preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - christian-kohler.npm-intellisense
    - eamodio.gitlens
    - genuitecllc.codetogether
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - leodevbro.blockman
    - meganrogge.template-string-converter
    - Gruntfuggly.todo-tree
    - PulkitGangwar.nextjs-snippets
    - bradlc.vscode-tailwindcss
