tasks:
  - name: Start development environment
    init: |
      eval $(command gp env -e)
      SHELL=$(which bash) npx --yes @teambit/bvm install
      source ~/.bashrc
      bit config set analytics_reporting false
      bit config set anonymous_reporting false
      pnpm config set auto-install-peers true
      git config pull.rebase false
    command: |
      bit config set user.token $BIT_TOKEN
      bit new svelte my-svelte-workspace --env bitdev.svelte/svelte-env
      bit scope set $BIT_SCOPE
      bit import $BIT_IMPORT
      # bit install
      # bit start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    description: Workspace components

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - christian-kohler.npm-intellisense
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - meganrogge.template-string-converter
    - leodevbro.blockman
    - Gruntfuggly.todo-tree
    - PKief.material-icon-theme
    - wix.vscode-import-cost

    # Git
    - eamodio.gitlens

    # ChatGPT / AI
    - Codeium.codeium

    ### Language Support
    # Svelte
    - svelte.svelte-vscode
    - fivethree.vscode-svelte-snippets
    - garlandcrow.vscode-svelte-pluskit-snippets

    # Tailwind
    - bradlc.vscode-tailwindcss

    # Env
    - IronGeek.vscode-env

    # Bit
    - https://pub-5513a9c56b7943fb986dd9a6abaea6c6.r2.dev/bit.vscode-bit-1.0.15.vsix
